apiVersion: v1
kind: Service
metadata:
  name: snipeit-nodeport
  namespace: snipeit
spec:
  type: NodePort
  selector:
    app: snipeit
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080